### PR TITLE
Mongoose

### LINKED ISSUE #43: rework backend to es6 and common js
current in es5. hence module.export = syntax.
lets update it.

### PR DESCRIPTION
**Pull request by tlee0818**
updated to es6 and changed directories and config files.
should only affect app/ directory

resolves #43

### CODE REVIEW

**Comment by ruilinfeng** [comment]
LGTM. Are we separating the functions into different files?

**Review by ollyplance — APPROVED** [review]
LGTM - assuming most of these changes are automated

**Review by ruilinfeng — APPROVED** [review]
LGTM. Are we separating the functions into different files?

**Comment by tlee0818** [comment]
> 

ye we should

**Pull request merged**
